name: FAR_B_GRPO_Long_dmlab_res64_1000K_bs32
manual_seed: 0
mixed_precision: bf16

# dataset and data loader settings
datasets:
  train:
    type: DMLabDataset
    data_list: /users/xiaokangliu/datasets/dmlab/dmlab_train.json
    split: training
    use_latent: false
    data_cfg:
      num_frames: 300
      frame_interval: 1
    batch_size_per_gpu: 8
    num_rollouts_per_prompt: 4 # currently for debug

  sample:
    type: DMLabDataset
    data_list: /users/xiaokangliu/datasets/dmlab/dmlab_val.json
    split: validation
    data_cfg:
      num_frames: 300
      frame_interval: 1
    num_sample: 256
    batch_size_per_gpu: 8

models:
  model_cfg:
    transformer:
      from_pretrained: ~ # diffusers pretrained path (from_pretrained)
      init_cfg:
        type: FAR_B_Long
        config: {
          "condition_cfg": {
            "type": "action",
            "num_action_classes": 4
          }
        }
        pretrained_path: /users/xiaokangliu/models/FAR_B_Long_DMLab_Action64-c09441dc.pth
    vae:
      type: MyAutoencoderDC
      from_config: options/model_cfg/dcae/model_8x_c32_config.json
      from_config_pretrained: /users/xiaokangliu/models/DCAE_DMLab_Res64-17035ae5.pth
    scheduler:
      from_pretrained: options/model_cfg/far/scheduler_config.json
  clean_context_ratio: 0.1
  weighting_scheme: logit_normal
  training_type: long_context

# path
path:
  pretrain_network: ~

# training settings
train:
  train_pipeline: FARTrainer

  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [ 0.9, 0.999 ]

  param_names_to_optimize: ~
  ema_decay: 0.9999

  lr_scheduler: constant_with_warmup
  warmup_iter: 10000
  total_iter: 1000000
  max_grad_norm: 1.0
  adv_clip_max: 5
  clip_range: 1e-4
  num_batches_per_epoch: 2

# validation settings
val:
  val_pipeline: FARPipeline
  val_freq: 50000
  sample_cfg:
    context_length: 144
    unroll_length: 56
    guidance_scale: 1.5
    num_inference_steps: 50
    sample_size: 8
    sample_trajectory_per_video: 1
    use_kv_cache: true
  eval_cfg:
    metrics: ['mse', 'psnr', 'ssim', 'fvd', 'lpips']

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 50000
  use_wandb: false
