name: ucfv7_jpeg_16fr_10st_GRPO_FAR_L_ucf101_uncond_res256_400K_bs32
manual_seed: 0
mixed_precision: bf16

# dataset and data loader settings
datasets:
  train:
    type: UCFDataset
    data_list: /users/xiaokangliu/datasets/ucf101/trainval.json
    split: training
    data_cfg:
      n_frames: 16
      resolution: 256
      frame_interval: 3
      use_flip: true
    batch_size_per_gpu: 16
    num_rollouts_per_prompt: 8

  sample:
    type: UCFDataset
    data_list: /users/xiaokangliu/datasets/ucf101/trainval.json
    split: validation
    data_cfg:
      n_frames: 16
      resolution: 256
      frame_interval: 3
      evaluation_type: Latte
    num_sample: 64
    batch_size_per_gpu: 16

models:
  model_cfg:
    transformer:
      from_pretrained: ~ # diffusers pretrained path (from_pretrained)
      init_cfg:
        type: FAR_L
        pretrained_path: /users/xiaokangliu/models/FAR_L_UCF101_Uncond256-adea51e9.pth
      lora_config:
        r: 32  # LoRA rank
        alpha: 64  # LoRA scaling factor
        dropout: 0.1
        target_modules: ["to_q", "to_k", "to_v", "to_out.0", "add_k_proj", "add_q_proj", "add_v_proj", "to_add_out"]  # Target attention modules for LoRA
        bias: "none"
        task_type: "FEATURE_EXTRACTION"
    vae:
      type: MyAutoencoderDC
      from_config: options/model_cfg/dcae/model_32x_c32_config.json
      from_config_pretrained: /users/xiaokangliu/models/DCAE_UCF101_Res256-9c4355c8.pth
    scheduler:
      from_pretrained: options/model_cfg/far/scheduler_config.json
  clean_context_ratio: 0.1
  weighting_scheme: logit_normal
  training_type: base

# path
path:
  pretrain_network: ~

# training settings
train:
  train_pipeline: FARTrainer

  optim_g:
    type: AdamW
    lr: !!float 5e-5
    weight_decay: 0
    betas: [ 0.9, 0.999 ]

  param_names_to_optimize: ~
  ema_decay: 0.9999

  lr_scheduler: constant_with_warmup
  warmup_iter: 100
  total_iter: 1000000
  max_grad_norm: 1.0
  adv_clip_max: 5
  clip_range: 5e-4
  # clip_range: 1e-2
  kl_weight: 0.001
  num_batches_per_epoch: 2
  reward: jpeg

# validation settings
val:
  val_pipeline: FARPipeline
  val_freq: 4000
  eval_on_start: false
  sample_cfg:
    context_length: 2
    unroll_length: 14
    guidance_scale: 1.0
    # num_inference_steps: 50
    num_inference_steps: 10
    sample_size: 8
    sample_steps_prob: 1
    sample_trajectory_per_video: 1
  eval_cfg:
    metrics: ['mse', 'psnr', 'ssim', 'fvd', 'lpips']

# logging settings
logger:
  print_freq: 5
  save_checkpoint_freq: !!float 5000
  use_wandb: true

